[package]
name = "dining_philosophers"
version = "0.1.0"
authors = ["tonarinohito <rsp44316@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# MacOSでは使えない（コンパイルエラーになる）
# device_query = "0.1.3"